apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user16-jump-app-cicd
  namespace: user16-gitops-argocd
spec:
  destination:
    namespace: user16-jump-app-cicd
    server: 'https://kubernetes.default.svc'
  project: jump-app
  source:
    path: .
    repoURL: 'https://github.com/nveces/jump-app-gitops.git'
    targetRevision: cicd
